"""initial schema

Revision ID: 8e035dbaed7f
Revises: 
Create Date: 2026-06-17 18:29:47.742570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e035dbaed7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tally_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('pushed_to_zoho', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('raw_payload_excerpt', sa.Text(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'accounts', 'sales', 'warehouse', 'guard', 'auditor', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('gate_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_number', sa.String(length=32), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('vendor_name', sa.String(length=256), nullable=False),
    sa.Column('vendor_zoho_id', sa.String(length=64), nullable=True),
    sa.Column('expected_items', sa.Text(), nullable=True),
    sa.Column('invoice_ref', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('created', 'unloaded', 'grn_done', 'closed', 'rejected', name='gateentrystatus'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_entries_entry_number'), 'gate_entries', ['entry_number'], unique=True)
    op.create_table('picklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picklist_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_number', sa.String(length=32), nullable=True),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('route', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus'), nullable=True),
    sa.Column('sales_order_refs', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picklists_picklist_number'), 'picklists', ['picklist_number'], unique=True)
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('scheme_type', sa.Enum('qty_slab', 'value_slab', 'flat_discount', 'bundle', name='schemetype'), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=True),
    sa.Column('min_margin_pct', sa.Float(), nullable=True),
    sa.Column('applicability', sa.JSON(), nullable=False),
    sa.Column('rule', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemes_code'), 'schemes', ['code'], unique=True)
    op.create_table('gate_entry_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_entry_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.String(length=256), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gate_entry_id'], ['gate_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_number', sa.String(length=32), nullable=False),
    sa.Column('gate_entry_id', sa.Integer(), nullable=True),
    sa.Column('vendor_zoho_id', sa.String(length=64), nullable=False),
    sa.Column('vendor_name', sa.String(length=256), nullable=False),
    sa.Column('invoice_ref', sa.String(length=64), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'pushed_to_zoho', 'failed', name='grnstatus'), nullable=False),
    sa.Column('zoho_purchase_bill_id', sa.String(length=64), nullable=True),
    sa.Column('zoho_credit_note_id', sa.String(length=64), nullable=True),
    sa.Column('zoho_error', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gate_entry_id'], ['gate_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grns_grn_number'), 'grns', ['grn_number'], unique=True)
    op.create_table('picklist_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picklist_id', sa.Integer(), nullable=False),
    sa.Column('item_zoho_id', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=256), nullable=False),
    sa.Column('bin_location', sa.String(length=64), nullable=True),
    sa.Column('ordered_qty', sa.Float(), nullable=True),
    sa.Column('picked_qty', sa.Float(), nullable=True),
    sa.Column('short_qty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['picklist_id'], ['picklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('zoho_invoice_id', sa.String(length=64), nullable=False),
    sa.Column('party_zoho_id', sa.String(length=64), nullable=False),
    sa.Column('party_name', sa.String(length=256), nullable=True),
    sa.Column('item_zoho_id', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=256), nullable=True),
    sa.Column('billed_qty', sa.Float(), nullable=True),
    sa.Column('free_qty', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('margin_pct_after', sa.Float(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_applications_zoho_invoice_id'), 'scheme_applications', ['zoho_invoice_id'], unique=False)
    op.create_table('grn_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('item_zoho_id', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=256), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('expected_qty', sa.Float(), nullable=True),
    sa.Column('received_qty', sa.Float(), nullable=False),
    sa.Column('shortage_qty', sa.Float(), nullable=True),
    sa.Column('damage_qty', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grn_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('photo_type', sa.String(length=32), nullable=True),
    sa.Column('caption', sa.String(length=256), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grn_photos')
    op.drop_table('grn_lines')
    op.drop_index(op.f('ix_scheme_applications_zoho_invoice_id'), table_name='scheme_applications')
    op.drop_table('scheme_applications')
    op.drop_table('picklist_lines')
    op.drop_index(op.f('ix_grns_grn_number'), table_name='grns')
    op.drop_table('grns')
    op.drop_table('gate_entry_images')
    op.drop_index(op.f('ix_schemes_code'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_picklists_picklist_number'), table_name='picklists')
    op.drop_table('picklists')
    op.drop_index(op.f('ix_gate_entries_entry_number'), table_name='gate_entries')
    op.drop_table('gate_entries')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('tally_sync_log')
    # ### end Alembic commands ###
