"""add zoho picklist id

Revision ID: 2b5e72d6de85
Revises: d4e5f6a7b8c9
Create Date: 2026-06-30 19:22:57.433000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5e72d6de85'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_orders', sa.Column('zoho_picklist_id', sa.String(length=64), nullable=True))
    op.alter_column('dispatch_orders', 'zoho_package_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_index('idx_dispatch_orders_packed_at', table_name='dispatch_orders')
    op.drop_index('idx_dispatch_orders_zoho_package_id', table_name='dispatch_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_dispatch_orders_zoho_package_id', 'dispatch_orders', ['zoho_package_id'], unique=False)
    op.create_index('idx_dispatch_orders_packed_at', 'dispatch_orders', ['packed_at'], unique=False)
    op.alter_column('dispatch_orders', 'zoho_package_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_column('dispatch_orders', 'zoho_picklist_id')
    # ### end Alembic commands ###
