"""add po line item id

Revision ID: 9032bf7869b3
Revises: b5d56ac1c48f
Create Date: 2026-06-25 18:46:22.186040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9032bf7869b3'
down_revision: Union[str, None] = 'b5d56ac1c48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grn_lines', sa.Column('po_line_item_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grn_lines', 'po_line_item_id')
    # ### end Alembic commands ###
