"""add purchase receive fields to grn

Revision ID: b5d56ac1c48f
Revises: d4d7dc96db90
Create Date: 2026-06-25 17:15:49.939420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d56ac1c48f'
down_revision: Union[str, None] = 'd4d7dc96db90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dispatch_orders_dispatch_number_key', 'dispatch_orders', type_='unique')
    op.drop_index('ix_dispatch_orders_number', table_name='dispatch_orders')
    op.create_index(op.f('ix_dispatch_orders_dispatch_number'), 'dispatch_orders', ['dispatch_number'], unique=True)
    op.add_column('grns', sa.Column('purchase_receive_number', sa.String(length=64), nullable=True))
    op.add_column('grns', sa.Column('received_date', sa.DateTime(), nullable=True))
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_index('ix_tally_outbound_status', table_name='tally_outbound_queue')
    op.drop_index('ix_tally_outbound_type', table_name='tally_outbound_queue')
    op.drop_index('ix_tally_outbound_zoho', table_name='tally_outbound_queue')
    op.create_index(op.f('ix_tally_outbound_queue_payload_type'), 'tally_outbound_queue', ['payload_type'], unique=False)
    op.create_index(op.f('ix_tally_outbound_queue_status'), 'tally_outbound_queue', ['status'], unique=False)
    op.create_index(op.f('ix_tally_outbound_queue_zoho_entity_id'), 'tally_outbound_queue', ['zoho_entity_id'], unique=False)
    op.drop_index('ix_zoho_contact_cache_group', table_name='zoho_contact_cache')
    op.drop_index('ix_zoho_contact_cache_type', table_name='zoho_contact_cache')
    op.drop_constraint('zoho_contact_cache_zoho_contact_id_key', 'zoho_contact_cache', type_='unique')
    op.create_index(op.f('ix_zoho_contact_cache_contact_type'), 'zoho_contact_cache', ['contact_type'], unique=False)
    op.create_index(op.f('ix_zoho_contact_cache_party_group'), 'zoho_contact_cache', ['party_group'], unique=False)
    op.create_index(op.f('ix_zoho_contact_cache_zoho_contact_id'), 'zoho_contact_cache', ['zoho_contact_id'], unique=True)
    op.drop_constraint('zoho_item_cache_zoho_item_id_key', 'zoho_item_cache', type_='unique')
    op.create_index(op.f('ix_zoho_item_cache_zoho_item_id'), 'zoho_item_cache', ['zoho_item_id'], unique=True)
    op.drop_index('ix_zoho_webhook_entity', table_name='zoho_webhook_events')
    op.drop_index('ix_zoho_webhook_event_type', table_name='zoho_webhook_events')
    op.create_index(op.f('ix_zoho_webhook_events_entity_id'), 'zoho_webhook_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_zoho_webhook_events_event_type'), 'zoho_webhook_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoho_webhook_events_event_type'), table_name='zoho_webhook_events')
    op.drop_index(op.f('ix_zoho_webhook_events_entity_id'), table_name='zoho_webhook_events')
    op.create_index('ix_zoho_webhook_event_type', 'zoho_webhook_events', ['event_type'], unique=False)
    op.create_index('ix_zoho_webhook_entity', 'zoho_webhook_events', ['entity_id'], unique=False)
    op.drop_index(op.f('ix_zoho_item_cache_zoho_item_id'), table_name='zoho_item_cache')
    op.create_unique_constraint('zoho_item_cache_zoho_item_id_key', 'zoho_item_cache', ['zoho_item_id'])
    op.drop_index(op.f('ix_zoho_contact_cache_zoho_contact_id'), table_name='zoho_contact_cache')
    op.drop_index(op.f('ix_zoho_contact_cache_party_group'), table_name='zoho_contact_cache')
    op.drop_index(op.f('ix_zoho_contact_cache_contact_type'), table_name='zoho_contact_cache')
    op.create_unique_constraint('zoho_contact_cache_zoho_contact_id_key', 'zoho_contact_cache', ['zoho_contact_id'])
    op.create_index('ix_zoho_contact_cache_type', 'zoho_contact_cache', ['contact_type'], unique=False)
    op.create_index('ix_zoho_contact_cache_group', 'zoho_contact_cache', ['party_group'], unique=False)
    op.drop_index(op.f('ix_tally_outbound_queue_zoho_entity_id'), table_name='tally_outbound_queue')
    op.drop_index(op.f('ix_tally_outbound_queue_status'), table_name='tally_outbound_queue')
    op.drop_index(op.f('ix_tally_outbound_queue_payload_type'), table_name='tally_outbound_queue')
    op.create_index('ix_tally_outbound_zoho', 'tally_outbound_queue', ['zoho_entity_id'], unique=False)
    op.create_index('ix_tally_outbound_type', 'tally_outbound_queue', ['payload_type'], unique=False)
    op.create_index('ix_tally_outbound_status', 'tally_outbound_queue', ['status'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.drop_column('grns', 'received_date')
    op.drop_column('grns', 'purchase_receive_number')
    op.drop_index(op.f('ix_dispatch_orders_dispatch_number'), table_name='dispatch_orders')
    op.create_index('ix_dispatch_orders_number', 'dispatch_orders', ['dispatch_number'], unique=False)
    op.create_unique_constraint('dispatch_orders_dispatch_number_key', 'dispatch_orders', ['dispatch_number'])
    # ### end Alembic commands ###
