"""zoho_picklist_line_item_id

Revision ID: c11d4c8ef62a
Revises: 2b5e72d6de85
Create Date: 2026-07-01 17:46:42.936424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11d4c8ef62a'
down_revision: Union[str, None] = '2b5e72d6de85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_lines', sa.Column('zoho_picklist_line_item_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_lines', 'zoho_picklist_line_item_id')
    # ### end Alembic commands ###
